# Principles of OOP

Encapsulation - implementation details are hidden or encapsulated in objects

Inheritance - child classes can inherit from parent classes and modules

Polymorphism - objects and names exist in many forms. So, the same attribute or method can exist in multiple classes and mean different things, etc.

Abstraction - handling a concept rather than the implementation details

# NumPy Overview

1. Arrays
2. Array shaping and transposition
3. Array math
4. Array indexing and slicing
5. array broadcasting

NumPy is all about arrays!

# Arrays

Structured list of numbers.

- Scalars
- Vectors
- Matrices
- Images
- Tensors
- ConvNets (Convulusional Neural Network)

In [7]:
# Arrays, Basic Properties

import numpy as np

a = np.array([[1,2,3], [4,5,6]], dtype = np.float32)

print(a.ndim, a.shape, a.dtype)

# Arrays can have any number of dimensions, including zero (a scalar).
# Arrays are typed: np.uint8, np.int64, np.float32, np.float64
# Arrays are dense. Each element of the array exists and has the same type.
# Arrays are faster than python lists (consume less memory).
# We can only combine arrays of the same shape!

2 (2, 3) float32


In [15]:
# Array Exercise

import numpy as np

# Make a three-dimensional array
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]], dtype = np.float32)

print(arr.ndim, arr.shape, arr.dtype)

# Make a 6D array
arr2 = np.array([[[1,2,3],[4,5,6],[7,8,9]]], ndmin = 6)
arr2

# np.ones((3, 2))
np.ones((3, 2))

3 (1, 3, 3) float32


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# Shaping

In [16]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [18]:
a = a.reshape(3, 2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
a = a.reshape(2, -1)
a

# -1 inverts the axes

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a = a.ravel()
a

array([1, 2, 3, 4, 5, 6])

In [24]:
b = np.arange(10).reshape(5, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [25]:
b = b.T
b

# Transposed; rows became columns, columns became rows

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [26]:
np.sqrt(b)

array([[0.        , 1.41421356, 2.        , 2.44948974, 2.82842712],
       [1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ]])

# Pandas

Python module used for data analysis and exploration

Two main useful data structures:
- Series
- DataFrames

Can import data files and turn them into DataFrames
- CSV (comma-separated values)

The documentation is pretty good!

Can handle medium sized data (not very good for truly big data)
- But each new release gets a bit better